---
#tags
Ambiente: PRODUCAO
Projeto: RANCHER

region: us-east-1

cidr_block: 10.0.0.0/16
cidr_public_a: 10.0.1.0/24
cidr_private_a: 10.0.2.0/24
cidr_public_b: 10.0.3.0/24
cidr_private_b: 10.0.4.0/24

key: everton.aulianNV

#Flavor:
node_instance_flavor: t2.micro
basion_host_instance_flavor: t2.micro

#Volume
node_rootdisk_size: 8
bastion_host_rootdisk_size: 8

cluster: |
  #!/bin/sh

  #Update OS
  yum update -y

  #Installing nfs-utils
  yum install nfs-utils

  #Disable Iptables
  iptables -F

  #Disabling Firewalld
  systemctl disable firewalld
  systemctl stop firewalld

  #Disabling selinux
  setenforce 0
  sed -i s/^SELINUX=.*$/SELINUX=disabled/ /etc/selinux/config

  #Change history time format
  echo "" >> /etc/profile
  echo '# History with Date
  export HISTTIMEFORMAT="%h/%d - %H:%M:%S " ' >> /etc/profile

  #Changing hostname
  echo "{{ item.server }}" > /etc/hostname
  hostname "{{ item.server }}"

  #Configure timezone
  timedatectl set-timezone America/Sao_Paulo

  #Install and configure auditd
  yum install audit audit-libs
  systemctl start auditd
  systemctl enable auditd 

  #Install docker 18.09.8
  yum install -y yum-utils device-mapper-persistent-data lvm2
  
  yum-config-manager -y --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  yum install -y docker-ce-18.09.8 docker-ce-cli-18.09.8 containerd.io

  #Run docker as non-root user.
  usermod -aG docker centos
  
  #Start Docker
  systemctl enable docker
  systemctl start docker

  #Remove docker from future updates
  echo exclude=docker* containerd* >> /etc/yum.config

  #Reboot Server
  reboot

bastion: |
  #!/bin/sh

  #Update OS
  yum update -y

  #Install packages
  yum -y install wget git

  #Disable Iptables
  iptables -F

  #Disabling Firewalld
  systemctl disable firewalld
  systemctl stop firewalld

  #Disabling selinux
  setenforce 0
  sed -i s/^SELINUX=.*$/SELINUX=disabled/ /etc/selinux/config

  #Change history time format
  echo "" >> /etc/profile
  echo '# History with Date
  export HISTTIMEFORMAT="%h/%d - %H:%M:%S " ' >> /etc/profile

  #Changing hostname
  echo "{{ item.server }}" > /etc/hostname
  hostname "{{ item.server }}"

  #Configure timezone
  timedatectl set-timezone America/Sao_Paulo

  #Install and configure auditd
  yum install audit audit-libs
  systemctl start auditd
  systemctl enable auditd

  #Copy key to server
  echo "{{ KEY }}" > ~/.ssh/k8s.pem
  chmod 400 ~/.ssh/*

  #Clone git repository with deploy configuration
  git clone https://github.com/evertonaulian/aulian-rke.git

  #Installing kubectl
  cat <<EOF > /etc/yum.repos.d/kubernetes.repo
  [kubernetes]
  name=Kubernetes
  baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
  enabled=1
  gpgcheck=1
  repo_gpgcheck=1
  gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  EOF
  yum install -y kubectl

  #Configure RKE
  wget https://github.com/rancher/rke/releases/latest/download/rke_linux-amd64
  mv rke_linux-amd64 rke
  chmod +x rke
  ./rke --version
  ./rke up --config ./aulian-rke/rancher-cluster.yml
  