---
#Security groups for Workers, etcs, and controlplane

- name: Creating security group for bastion host
  ec2_group:
    region: "{{ region }}"
    name: sg_bastion_host
    description: sg_bastion_host
    vpc_id: "{{ vpc.vpc.id }}"
    purge_rules: yes
    purge_tags: yes
    state: present
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: "{{ PUBLICIP }}/32"
        rule_desc: HTTP Access

- name: Creating security group for workers
  ec2_group:
    region: "{{ region }}"
    name: sg_workers
    description: sg_workers
    vpc_id: "{{ vpc.vpc.id }}"
    purge_rules: yes
    purge_tags: yes
    state: present
    rules:
      - proto: all
        group_name: sg_workers
        rule_desc: Allowing internal communication between workers
      - proto: tcp
        ports:
          - 6443
        group_name: sg_bastion_host
        rule_desc: KubeAPI port
      - proto: tcp
        ports:
          - 22
        group_name: sg_bastion_host
        rule_desc: SSh Access from bastion host