---
- name: Creating Workers
  ec2_instance:
    filters: 
      tag:Name: "{{ item.server }} - {{ item.description }}"
    region: "{{region}}"
    key_name: "{{key}}"
    instance_type: "{{ node_instance_flavor }}"
    image_id: "{{ centos.images[0].image_id }}"
    vpc_subnet_id: "{{ item.subnet }}"
    termination_protection: yes
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: "{{ node_rootdisk_size }}"
          volume_type: gp2
          delete_on_termination: true
          encrypted: false
    tags:
      Name: "{{ item.server }} - {{ item.description }}"
      Ambiente: "{{ Ambiente }}"
      Projeto: "{{ Projeto }}"
    network:
      assign_public_ip: true #Must be changed later, I'm using the public ip now just because a do not want to pay for a NatGateway
      private_ip_address: "{{ item.ipaddress }}" #Must be improved to do not depend on fixed IP address
    security_groups: sg_workers
    user_data: "{{ cluster }}"
  loop:
    - { server: 'AWSK8SXED-PD-01', description: 'ETCD', subnet: "{{ private_subnet_facts.results[0].subnets | map(attribute='subnet_id') | list | first }}", ipaddress: 10.0.2.100}
    - { server: 'AWSK8SXCP-PD-02', description: 'CONTROLPLANE', subnet: "{{ private_subnet_facts.results[1].subnets | map(attribute='subnet_id') | list | first }}", ipaddress: 10.0.4.100}
    - { server: 'AWSK8SXWK-PD-03', description: 'WORKER', subnet: "{{ private_subnet_facts.results[0].subnets | map(attribute='subnet_id') | list | first }}", ipaddress: 10.0.2.110}
    - { server: 'AWSK8SXWK-PD-04', description: 'WORKER', subnet: "{{ private_subnet_facts.results[1].subnets | map(attribute='subnet_id') | list | first }}", ipaddress: 10.0.4.110}